### ISSUE TITLE
Changing the reference in multiple comparisons

### ISSUE THREAD

**Issue by joliveiracosta** [giabaio/BCEA#4]
Hi, I would like to plot a comparison of A, B, C, with A as the reference.
Using the standard ceplane.plot, it plots A-B, and A-C.
However, I wanted to show B-A and C-A.
Is it possible to change it?

**Comment by giabaio** [comment]
Hi Juliana,
In BCEA terminology, the "reference" intervention is the one you're assessing to see if it's more cost-effective than the comparator(s). That's why it produces the plots in terms of A vs B and A vs C, because the analysis is all about A vs the others (assuming A is your "reference" intervention). Why exactly do you want B vs A and C vs A? 

In any case, the simplest solution is to use the output to the call to `bcea` and slightly modify it to get ceplane.plot to do what you want, for example
```
library(BCEA)
data(Smoking)
m=bcea(e,c,ref=4)
m2=m
m2$delta.e=-m2$delta.e
m2$deltac=-m2$delta.c
m2$ref=m$comp
m2$comp=m$ref
ceplane.plot(m2)
```
This way, you obtain the plots in the format you want --- the price to pay (eg duplicate the `bcea` object and then modify some of its elements) seems minimal... I am happy to think about modifying the actual function if you have a strong rationale for wanting the plot the way you mention, though!

HTH
Gianluca

**Comment by joliveiracosta** [comment]
Hi Gianluca,
In the perspective I am conducting the CEA, the reference is the standard treatment (sometimes known as the available treatment already offered in the Health Care System), and the other alternatives should be compared against it, as they are newly launched technologies.  That is why I wanted to know if the new ones are cost-effective compared to the "reference". 
I have run the code you provided and it worked perfectly. I just corrected the 6th line, where m2$delta.c  was missing the ".".
Thank you for your support!  
Cheers,
